cooldown:
    universal: true
    alert message: It's been too soon since your last shout!
    ready message: Your Thu'um is ready.
    persistence: 100
shouts:
    fusrodah:
        - 15
        - 20
        - 45
    yoltoorshul:
        - 30
        - 50
        - 100
    lokvahkoor:
        - 5
        - 10
        - 15
    kaandremov:
        - 40
        - 50
        - 60
    wuldnahkest:
        - 20
        - 25
        - 35
    feimziigron:
        - 20
        - 30
        - 40
    laasyahnir:
        - 30
        - 40
        - 50